export const bookImageMap = {
  "img/olvido.png": require("../assets/img/olvido.png"),
  "img/cienaños.png": require("../assets/img/cienaños.png"),
  "img/delirio.png": require("../assets/img/delirio.png"),
  "img/voragine.png": require("../assets/img/voragine.png"),
  "img/ruido.png": require("../assets/img/ruido.png"),
  "img/satanas.png": require("../assets/img/satanas.png"),
  "img/coronel.png": require("../assets/img/coronel.png"),
  "img/laperra.png": require("../assets/img/laperra.png"),
  "img/quijote.png": require("../assets/img/quijote.png"),
  "img/islatesoro.png": require("../assets/img/islatesoro.png"),
  "img/diners.png": require("../assets/img/diners.png"),
  "img/cromos.png": require("../assets/img/cromos.png"),
  "img/portafolio.png": require("../assets/img/portafolio.png"),
  "img/arcadia.png": require("../assets/img/arcadia.png"),
  "img/poder.png": require("../assets/img/poder.png"),
  "img/vogue.png": require("../assets/img/vogue.png"),
  "img/hombre-sentido.png": require("../assets/img/hombre-sentido.png"),
  "img/casadeespiritus.png": require("../assets/img/casadeespiritus.png"),
  "img/soho.png": require("../assets/img/soho.png"),
  "img/natgeo.png": require("../assets/img/natgeo.png"),
};